export default {
  DETAILS_APP_1: "/details/app-ban-hang",
  DETAILS_APP_2: "/details/app-doanh-nghiep",
  DETAILS_APP_3: "/details/app-tai-chinh",
  DETAILS_APP_4: "/details/app-y-te",
  DETAILS_APP_5: "/details/app-giao-duc",
  DETAILS_APP_6: "/details/app-du-lich",
  DETAILS_APP_7: "/details/app-an-uong",
  DETAILS_APP_8: "/details/app-van-chuyen",
  DETAILS_APP_9: "/details/app-hen-ho",
  DETAILS_WEB_1: "/details/web-ban-hang",
  DETAILS_WEB_2: "/details/web-doanh-nghiep",
  DETAILS_WEB_3: "/details/web-tai-chinh",
  DETAILS_WEB_4: "/details/web-y-te",
  DETAILS_WEB_5: "/details/web-giao-duc",
  DETAILS_WEB_6: "/details/web-du-lich",
  DETAILS_WEB_7: "/details/web-am-thuc",
  DETAILS_WEB_8: "/details/web-van-chuyen",
  DETAILS_WEB_9: "/details/web-hen-ho",
};
